replicaCount: 1

app:
  name: flask-app
  label: flask

image:
  repository: sagarbompada/flask-app
  tag: latest

imagePullSecret: ecr-secret

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30007
